apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scaup-frontend
  title: Scaup Frontend
  description: A web application for sample shipping, definition, and experiment parametrisation
spec:
  type: website
  lifecycle: experimental
  system: scaup
  owner: group:lims
  dependsOn:
    - component:web-ui-components
  consumesApis:
    - scaup-api
